config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates_presence_of :content
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates_presence_of :title, :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]

  def new
    @comment = @post.comments.new
  end

  def create
   head :unprocessable_entity unless @comment = @post.comments.create(comment_params)
  end

  def edit
  end

  def update
    @comment.update(comment_params)
  end

  def destroy
    @comment.destroy
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id]) if @post
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
  end

  def show
  end

  def edit
    render 'new'
  end

  def update
    @post.update(post_params)
  end

  def destroy
    @post.destroy
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
%li[comment]
  = comment.content
  %a.dropdown-toggle.pull-right{'data-toggle': 'dropdown', type: 'button'}
    %i.fa.fa-pie-chart
    %span.caret{'title': 'opciones'}
  %ul.dropdown-menu.pull-right
    %li
      = link_to 'Editar', edit_post_comment_path(comment.post_id, comment.id), remote: true
    %li
      = link_to 'Eliminar', post_comment_path(comment.post_id, comment.id), method: :delete, remote: true

app/views/comments/_form.html.haml
= form_for [@comment.post, @comment], remote: true do |f|
  .form-group.col-sm-8
    = f.text_area :content, class: 'form-control', placeholder: 'Escribe tu comentario...'
    %span.help-block.with-errors#content_error
  .form-group.col-sm-6
    = f.submit 'Comentar'

app/views/comments/create.js.erb
$("<%= j render @comment %>")
.appendTo($('#comments'))
.effect('highlight', null, 2000);

app/views/comments/destroy.js.erb
$("#comment_<%= @comment.id %>").hide();

app/views/comments/edit.js.erb
$('#form-comment').html("<%= j render 'form' %>");

app/views/comments/new.js.erb
$('#form-comment').html("<%= j render 'form' %>");

$('#form-comment').on('ajax:before', function(e, xhr, status, error){
  f = $(e.currentTarget);
  content = f.find('#comment_content').val();

  if (content === ''){
    $('#content_error').append('Comentario es obligatorio.');
    return false;
  }
});

$('#form-comment form').on('ajax:success', function(e, xhr, status, error){
  $('#form-comment form').trigger('reset');
});

$('#form-comment form').on('ajax:error', function(e, xhr, status, error){
  alert('Error al guardar el comentario.');
});

app/views/comments/update.js.erb
$("#edit_comment_<%= @comment.id %>").hide();
$("<%= j render @comment %>")
.replaceAll($("#comment_<%= @comment.id %>"))
.effect('highlight', null, 2000);

app/views/layouts/application.html.haml
%html
  %head
    %title Blogpost
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = yield

app/views/posts/_form.html.haml
#dialog_form.modal.inmodal
  .modal-dialog
    .modal-content
      .modal-body
        = form_for @post, remote: true do |f|
          .form-group
            = f.label :title, class: 'form-label'
            = f.text_field :title, class: 'form-control'
            %span.help-block.with-errors#title_error
          .form-group
            = f.label :content, class: 'form-label'
            = f.text_area :content, class: 'form-control'
            %span.help-block.with-errors#content_error
          .form-group
            = f.submit 'Guardar', class: 'btn btn-success'
            = link_to 'Cancelar', '#', class: 'btn btn-danger btn-cancel'

app/views/posts/_post.html.haml
%li[post]
  = link_to post.title, post_path(post.id)
  %a.dropdown-toggle.pull-right{'data-toggle': 'dropdown', type: 'button'}
    %i.fa.fa-pie-chart
    %span.caret{'title': 'opciones'}
  %ul.dropdown-menu.pull-right
    %li
      = link_to 'Editar', edit_post_path(post.id), remote: true
    %li
      = link_to 'Eliminar', post_path(post.id), remote: true, method: :delete

app/views/posts/create.js.erb
$("<%= j render @post %>")
.appendTo($('#posts'))
.effect('highlight', null, 2000);

app/views/posts/destroy.js.erb
$("#post_<%= @post.id %>").hide();

app/views/posts/index.html.haml
.container
  .row
    .col-lg-12
      .margin-tb
        %h3 Publicaciones
        = link_to 'Publicar', new_post_path, remote: true, class: 'btn btn-success pull-right'
    .col-md-10
      .row
        %ul#posts.col-sm-6
          = render @posts

app/views/posts/new.js.erb
var dialog_form = $("<%= j render 'form' %>").dialog({
  autoOpen: false,
  width: 520,
  modal: true,
  close: function(){ dialog_form.dialog('destroy') }
});

$('#dialog_form .btn-cancel').click(function(){
  dialog_form.dialog('destroy');
  return false
});

$('#dialog_form form').on('ajax:before', function(e, xhr, status, error){
  f = $(e.currentTarget);
  title = f.find('#post_title').val();
  content = f.find('#post_content').val();

  if (title === ''){
    $('#title_error').append('Titúlo es obligatorio.');
    return false;
  }

  if (content === ''){
    $('#content_error').append('Conenido es obligatorio.');
    return false;
  }

});

$('#dialog_form form').on('ajax:success', function(e, xhr, status, error){
  dialog_form.dialog('close');
});

$('#dialog_form form').on('ajax:error', function(e, xhr, status, error){
  alert('Error to save');
});

dialog_form.dialog('open');

app/views/posts/show.html.haml
.container
  .row
    .col-lg-12
      .margin-tb
        %h1= @post.title
        %h4= @post.content
        = link_to 'Comentar', new_post_comment_path(@post.id), remote: true, class: 'btn btn-success pull-right'
      %h4 comentarios:
      .row
        %ul#comments.col-sm-6
          - @post.comments.each do |comment|
            = render comment
      #form-comment.row

app/views/posts/update.js.erb
$("<%= j render @post %>")
.replaceAll($("#post_<%= @post.id %>"))
.effect('highlight', null, 2000);